// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Todo struct {
	// ID
	ID int64 `json:"id"`
	// 标题
	Title string `json:"title"`
	// 描述
	Description pgtype.Text `json:"description"`
	// 是否完成
	Completed bool `json:"completed"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
