// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppCache struct {
	// 键
	Key string `json:"key"`
	// 值
	Value []byte `json:"value"`
	// 过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	// 键
	Key string `json:"key"`
	// 值
	Value string `json:"value"`
	// 描述
	Description pgtype.Text `json:"description"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Todo struct {
	// ID
	ID int64 `json:"id"`
	// 标题
	Title string `json:"title"`
	// 描述
	Description pgtype.Text `json:"description"`
	// 是否完成
	Completed bool `json:"completed"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
