// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 缓存
type AppCache struct {
	// 键
	Key string `json:"key"`
	// 值
	Value []byte `json:"value"`
	// 过期时间
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 邮箱
type Email struct {
	// ID
	ID int64 `json:"id"`
	// 用户ID
	UserID int64 `json:"user_id"`
	// 邮箱地址
	Email string `json:"email"`
	// 是否为主要邮箱
	IsPrimary bool `json:"is_primary"`
	// 是否已验证
	IsVerified bool `json:"is_verified"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 系统设置
type Setting struct {
	// 键
	Key string `json:"key"`
	// 值
	Value string `json:"value"`
	// 描述
	Description pgtype.Text `json:"description"`
	// 更新时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 待办事项
type Todo struct {
	// ID
	ID int64 `json:"id"`
	// 标题
	Title string `json:"title"`
	// 描述
	Description pgtype.Text `json:"description"`
	// 是否完成
	Completed bool `json:"completed"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 用户
type User struct {
	// ID
	ID int64 `json:"id"`
	// 用户名
	Username string `json:"username"`
	// 密码
	Password    string             `json:"password"`
	Nickname    pgtype.Text        `json:"nickname"`
	RegisterAt  pgtype.Timestamptz `json:"register_at"`
	IsValidated bool               `json:"is_validated"`
	ValidatedAt pgtype.Timestamptz `json:"validated_at"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
