// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTodos = `-- name: CountTodos :one
SELECT COUNT(*) FROM todos
`

func (q *Queries) CountTodos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (user_id, email, is_primary, is_verified)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, email, is_primary, is_verified, created_at
`

type CreateEmailParams struct {
	UserID     int64  `json:"user_id"`
	Email      string `json:"email"`
	IsPrimary  bool   `json:"is_primary"`
	IsVerified bool   `json:"is_verified"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRow(ctx, createEmail,
		arg.UserID,
		arg.Email,
		arg.IsPrimary,
		arg.IsVerified,
	)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IsPrimary,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (title, description, completed)
VALUES ($1, $2, $3)
RETURNING id, title, description, completed, created_at
`

type CreateTodoParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   bool        `json:"completed"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, arg.Title, arg.Description, arg.Completed)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, nickname)
VALUES ($1, $2, $3)
RETURNING id, username, password, nickname, register_at, is_validated, validated_at, created_at
`

type CreateUserParams struct {
	Username string      `json:"username"`
	Password string      `json:"password"`
	Nickname pgtype.Text `json:"nickname"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.Nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.RegisterAt,
		&i.IsValidated,
		&i.ValidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM app_cache
WHERE key = $1
`

// 删除一个缓存项
func (q *Queries) DeleteCache(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteCache, key)
	return err
}

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings
WHERE key = $1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSetting, key)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getCache = `-- name: GetCache :one

SELECT value, expires_at FROM app_cache
WHERE key = $1
`

type GetCacheRow struct {
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// 缓存 ===============================
// 获取一个缓存项，同时返回它的值和过期时间
func (q *Queries) GetCache(ctx context.Context, key string) (GetCacheRow, error) {
	row := q.db.QueryRow(ctx, getCache, key)
	var i GetCacheRow
	err := row.Scan(&i.Value, &i.ExpiresAt)
	return i, err
}

const getEmail = `-- name: GetEmail :one
SELECT id, user_id, email, is_primary, is_verified, created_at FROM emails
WHERE id = $1
`

func (q *Queries) GetEmail(ctx context.Context, id int64) (Email, error) {
	row := q.db.QueryRow(ctx, getEmail, id)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IsPrimary,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailByAddress = `-- name: GetEmailByAddress :one
SELECT id, user_id, email, is_primary, is_verified, created_at FROM emails
WHERE email = $1
`

func (q *Queries) GetEmailByAddress(ctx context.Context, email string) (Email, error) {
	row := q.db.QueryRow(ctx, getEmailByAddress, email)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.IsPrimary,
		&i.IsVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one

SELECT key, value, description, updated_at FROM settings
WHERE key = $1
`

// 系统设置 ===============================
func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, title, description, completed, created_at FROM todos
WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, username, password, nickname, register_at, is_validated, validated_at, created_at FROM users
WHERE id = $1
`

// 用户 ===============================
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.RegisterAt,
		&i.IsValidated,
		&i.ValidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, nickname, register_at, is_validated, validated_at, created_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.RegisterAt,
		&i.IsValidated,
		&i.ValidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEmails = `-- name: ListEmails :many

SELECT id, user_id, email, is_primary, is_verified, created_at FROM emails
`

// 邮箱 ================================
func (q *Queries) ListEmails(ctx context.Context) ([]Email, error) {
	rows, err := q.db.Query(ctx, listEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IsPrimary,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailsByUserId = `-- name: ListEmailsByUserId :many
SELECT id, user_id, email, is_primary, is_verified, created_at FROM emails
WHERE user_id = $1
`

func (q *Queries) ListEmailsByUserId(ctx context.Context, userID int64) ([]Email, error) {
	rows, err := q.db.Query(ctx, listEmailsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Email
	for rows.Next() {
		var i Email
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.IsPrimary,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, description, updated_at FROM settings
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many

SELECT id, title, description, completed, created_at FROM todos
ORDER BY id
`

// 待办事项 ===============================
func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password, nickname, register_at, is_validated, validated_at, created_at FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Nickname,
			&i.RegisterAt,
			&i.IsValidated,
			&i.ValidatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeExpiredCache = `-- name: PurgeExpiredCache :exec
DELETE FROM app_cache
WHERE expires_at < NOW()
`

// 清理所有已经过期的缓存项
func (q *Queries) PurgeExpiredCache(ctx context.Context) error {
	_, err := q.db.Exec(ctx, purgeExpiredCache)
	return err
}

const setCache = `-- name: SetCache :exec
INSERT INTO app_cache (key, value, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    expires_at = EXCLUDED.expires_at
`

type SetCacheParams struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// 使用 UPSERT (INSERT ... ON CONFLICT) 来设置缓存，这是原子操作
func (q *Queries) SetCache(ctx context.Context, arg SetCacheParams) error {
	_, err := q.db.Exec(ctx, setCache, arg.Key, arg.Value, arg.ExpiresAt)
	return err
}

const setSetting = `-- name: SetSetting :one
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = NOW()
RETURNING key, value, description, updated_at
`

type SetSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, setSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE emails
SET is_primary = $2, is_verified = $3
WHERE id = $1
`

type UpdateEmailParams struct {
	ID         int64 `json:"id"`
	IsPrimary  bool  `json:"is_primary"`
	IsVerified bool  `json:"is_verified"`
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.ID, arg.IsPrimary, arg.IsVerified)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET title = $2, description = $3, completed = $4
WHERE id = $1
`

type UpdateTodoParams struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Completed   bool        `json:"completed"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.Exec(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Completed,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2
WHERE id = $1
RETURNING id, username, password, nickname, register_at, is_validated, validated_at, created_at
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Nickname,
		&i.RegisterAt,
		&i.IsValidated,
		&i.ValidatedAt,
		&i.CreatedAt,
	)
	return i, err
}
